version: '3.8'

services:
  php_volumes:
    image: tianon/true
    volumes:
      - ./code:/var/www/html

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: deploy
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3307:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql

#  php:
#    build: ./build/php
#    volumes_from:
#      - php_volumes
#    volumes:
#      - ./config/php/no_xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#    depends_on:
#      - mysql
#    env_file:
#      - ./env/php.env

  php_xdebug:
    build: ./build/php
    volumes_from:
      - php_volumes
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/simple-server-php.ini
    depends_on:
      - mysql
    env_file:
      - ./env/php.env

  nginx:
    image: nginx:latest
    expose:
      - 80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
#    command: /bin/bash -c "envsubst '$$PHP_HOST $$PHP_PORT $$PHP_HOST_XDEBUG $$PHP_PORT_XDEBUG' < /etc/nginx/conf.d/switch.template > /etc/nginx/conf.d/switch.conf && nginx -g 'daemon off;'"

volumes:
  code:
  mysql:

networks:
  magento2:
    driver: bridge

